
[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
